export const mock: Product[] = [
  {
    _id: crypto.randomUUID(),
    name: "Flor Rosa",
    brightness: "Brillo",
    description: "Cuadro tipo bastidor autoadhesivo, en madera mdf 9mm.",
    price: 4200,
    size: "15x21",
    assetPath: "rose.avif",
  },
  {
    _id: crypto.randomUUID(),
    name: "Luna en Borde",
    brightness: "Brillo",
    description: "Cuadro tipo bastidor autoadhesivo, en madera mdf 9mm.",
    price: 4200,
    size: "15x21",
    assetPath: "moon.avif",
  },
  {
    _id: crypto.randomUUID(),
    name: "Monumento Democracia",
    brightness: "Mate",
    description: "Cuadro tipo bastidor autoadhesivo, en madera mdf 9mm.",
    size: "15x21",
    price: 4200,
    assetPath: "monument.avif",
  },
  {
    _id: crypto.randomUUID(),
    name: "Flores Fanta",
    brightness: "Mate",
    description: "Cuadro tipo bastidor autoadhesivo, en madera mdf 9mm.",
    price: 4200,
    size: "15x21",
    assetPath: "fanta.avif",
  },
  {
    _id: crypto.randomUUID(),
    name: "Flor Roja",
    brightness: "Brillo",
    description: "Cuadro tipo bastidor autoadhesivo, en madera mdf 9mm.",
    price: 4200,
    size: "15x21",
    assetPath: "red.avif",
  },
  {
    _id: crypto.randomUUID(),
    name: "Mural Messi",
    brightness: "Mate",
    description: "Cuadro tipo bastidor autoadhesivo, en madera mdf 9mm.",
    price: 8200,
    size: "20x30",
    assetPath: "messi.avif",
  },
  {
    _id: crypto.randomUUID(),
    name: "Bailarina (Negra)",
    brightness: "Mate",
    description: "Cuadro tipo bastidor autoadhesivo, en madera mdf 9mm.",
    price: 8200,
    size: "20x30",
    assetPath: "black-dancegirl.avif",
  },
  {
    _id: crypto.randomUUID(),
    name: "Bailarina (Rosa)",
    brightness: "Mate",
    description: "Cuadro tipo bastidor autoadhesivo, en madera mdf 9mm.",
    price: 8200,
    size: "20x30",
    assetPath: "pink-dancegirl.avif",
  },
];
